- name: "java_facts"
  copy: 
    content: >
      {
        "version": "{{ java_version.stdout }}",
        "build": "{{ java_build.stdout }}",
        "installed": "{{ ansible_date_time.date }}"
      }
    dest: /etc/ansible/facts.d/java.fact
  become: yes
