# -*- mode: ruby -*
# vi: set ft=ruby :

BOX_IMAGE = "my/centos7"
  
Vagrant.configure("2") do |config|
    config.vm.define "webserver" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "webserver"
      subconfig.vm.network :private_network, ip: "192.168.56.11"

      subconfig.vm.provider "virtualbox" do |vb|
        vb.name = "webserver-vm"
        vb.memory = "2048"
      end

    end
    config.vm.define "appserver" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "appserver"
      subconfig.vm.network :private_network, ip: "192.168.56.33"

      subconfig.vm.provider "virtualbox" do |vb|
        vb.name = "appserver-vm"
        vb.memory = "2048"
      end 
    end
end