- name: upgrade all packages, excluding kernel
  yum:
    name: '*'
    state: latest
    exclude: kernel*
  become: yes

- name: check if facts.d exhists
  file:
    path: /etc/ansible/facts.d
    recurse: yes
    state: directory
  become: yes
  notify: basic_facts


  
  